# Generated by Django 3.0.5 on 2020-04-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('summary', models.TextField(default='')),
                ('quote', models.TextField(blank=True)),
                ('pub_date', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagname', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=30)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('book', models.ManyToManyField(blank=True, to='app.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default='')),
                ('rating', models.FloatField(default='')),
                ('book', models.ManyToManyField(to='app.Book')),
                ('username', models.ManyToManyField(to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
